version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - '5672:5672'   # Porta para conexão
      - '15672:15672' # Porta do painel de controle (caso use rabbitmq-management)
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pgdata:
