spring:
  application:
    name: devpoc

  datasource:
    url: jdbc:postgresql://db:5432/devdb
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    clean-disabled: true
    validate-on-migrate: true
    out-of-order: false
    placeholders:
      schema_name: public
    schemas:
      - public
    table: flyway_schema_history
    mixed: false
    encoding: UTF-8

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true

server:
  error:
    whitelabel:
      enabled: false
  port: 3333
  servlet:
    contextPath: /api
  forward-headers-strategy: framework
