spring:
  application:
    name: devpoc

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    clean-disabled: true
    validate-on-migrate: true
    out-of-order: false
    placeholders:
      schema_name: public
    schemas:
      - public
    table: flyway_schema_history
    mixed: false
    encoding: UTF-8

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 50
    show-sql: true
    open-in-view: true

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topic:
      name: marketing-topic

server:
  error:
    whitelabel:
      enabled: false
  port: 3333
  servlet:
    contextPath: /api
  forward-headers-strategy: framework

rabbitmq:
  queue:
    name: marketing-queue
  exchange:
    name: marketing-exchange
  routing:
    key: marketing-routing-key
